import express from "express";
import uploadRoutes from "./uploadRoutes.js";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import dishRoutes from "./dishRoutes.js";
import menuRoutes from "./menuRoutes.js";
import tableRoutes from "./tableRoutes.js";
import reservationRoutes from "./reservationRoutes.js";
import reservationTableRoutes from "./reservationtableRoutes.js";
import invoiceRoutes from "./invoiceRoutes.js";
import invoiceDetailRoutes from "./invoicedetailRoutes.js";
import reviewRoutes from "./reviewRoutes.js";
const router = express.Router();
router.use("/upload", uploadRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/dishes", dishRoutes);
router.use("/menus", menuRoutes);
router.use("/tables", tableRoutes);
router.use("/reservations", reservationRoutes);
router.use("/reservation-tables", reservationTableRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/invoice-details", invoiceDetailRoutes);
router.use("/reviews", reviewRoutes);
export default router;
