import express from "express";
import uploadRoutes from "./uploadRoutes.js";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import dishRoutes from "./dishRoutes.js";
import menuRoutes from "./menuRoutes.js";
const router = express.Router();
router.use("/upload", uploadRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/dishes", dishRoutes);
router.use("/menus", menuRoutes);
export default router;
